# .github/workflows/generate.yml
name: Generate AI Posts

on:
  schedule:
    - cron: '0-59 6-11 * * *' # Random minute between 6 AM and 11 AM UTC
  workflow_dispatch:   # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install openai

      - name: Run Post Generation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_posts.py

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add generated_posts/*.md
          git commit -m "Auto-generate post [skip ci]" || echo "No changes to commit"
          git push